#
APP_HOST = 'localhost'
APP_PORT = 3001

# TICKETS
APP_PER_PAGE_ITEM_COUNT = 25

# CLIENT
ENV_KEY_CLIENT_ID = 'CLIENT_ID'
ENV_KEY_CLIENT_SECRET = 'CLIENT_SECRET'

# USER
ENV_KEY_DOMAIN = 'DOMAIN'
ENV_KEY_USERNAME = 'USERNAME'
ENV_KEY_PASSWORD = 'PASSWORD'

# TMP FILE
URI_RESOURCE_FILE = 'tmp/resource.txt'
URI_USER_DATA_FILE = 'tmp/user_data.txt'
URI_DOMAIN_DATA_FILE = 'tmp/domain'

# COOKIE
KEY_COOKIE_NAME = 'owat'

# TODO :: DELETE
ENV_KEY_DOMAIN_1 = 'DOMAIN_1'
ENV_KEY_USERNAME_1 = 'USERNAME_1'
ENV_KEY_PASSWORD_1 = 'PASSWORD_1'
